services:
  forker:
    image: forker
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
  scraper:
    image: nitter-scraper
    build: ../nitter-scraper
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/nitter-scraper:/usr/src/app/db
